version: '3.8'

services:
  backend:
    image: ghcr.io/ton-user/backend:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitoring

  frontend:
    image: ghcr.io/ton-user/frontend:latest
    restart: always
    ports:
      - "3000:80"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  monitoring:

volumes:
  grafana-storage:
